title: sebanalysis
email: sebanalysis@protonmail.com
description: >-
  A place to learn about the taxonomy of things.
twitter_username: sebanalysis
github_username: sebanalysis
theme: minima


plugins:
  - jekyll-feed
  - jekyll-include-cache
